# Generated by Django 3.2 on 2021-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_room_id',
            field=models.IntegerField(default=0),
        ),
    ]
