# Generated by Django 3.2.4 on 2021-07-20 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_artist',
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
    ]
