# Generated by Django 3.2.4 on 2021-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_artist',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
