# Generated by Django 3.2.4 on 2021-07-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_track_track_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
