# Generated by Django 3.2 on 2021-04-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='code',
            new_name='invitation_code',
        ),
    ]
