# Generated by Django 3.2.13 on 2022-05-11 21:40

from django.db import migrations


def move_spotify_playlists(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Spotify_Playlist = apps.get_model("spotify", "Playlist")
    Playlist_Playlist = apps.get_model("playlist", "Playlist")

    for spotify_playlist in Spotify_Playlist.objects.all():
        playlist_playlist = Playlist_Playlist.objects.create(
            room=spotify_playlist.room,
            created_by=spotify_playlist.created_by,
            created_at=spotify_playlist.created_at,
            ext_playlist_id=spotify_playlist.playlist_id,
            playlist_name=spotify_playlist.playlist_name,
        )


def move_spotify_tracks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Spotify_Track = apps.get_model("spotify", "Track")
    Playlist_Track = apps.get_model("playlist", "Track")

    for spotify_track in Spotify_Track.objects.all():
        playlist_track = Playlist_Track.objects.create(
            playlist_id=spotify_track.playlist,
            ext_track_id=spotify_track.track_id,
            track_name=spotify_track.track_name,
            track_artist=spotify_track.track_artist,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0003_delete_vote"),
        ("playlist", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(move_spotify_playlists),
        migrations.RunPython(move_spotify_tracks),
    ]